config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  # TODO: here we creating the custom route
  # todo to create the custom route we have to tell the controller and action name,
  get 'member/:id', to: 'members#show', as: 'member'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,  and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  Profile_title = [
    "Front-End Developers",
    "Back-End Developers",
    "Full-Stack Developers",
    "Mobile App Developers",
    "Game Developers",
    "DevOps Engineers",
    "Data Scientists",
    "Machine Learning Engineers",
    "Cybersecurity Experts",
    "UI/UX Designers"
  ].freeze

  def self.ransackable_attributes(_auth_object = nil)
    ["city", "country"]
  end

  def self.ransackable_associations(_auth_object = nil)
    []
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = User.ransack(params[:q])
    @user = @q.result.limit(25)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/home/index.html.erb
<br><br>
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
    <div class="input-group rounded">
      <%= search_form_for @q, url: root_path do |form| %>
        <%= form.search_field :city_or_country_cont, class: "form-control", placeholder: "Search by city or country", aria: { describedby: "search-addon" } %>
        <%= form.submit "Search", class:"btn btn-primary", id: "search-addon" %>
      <% end %>
    </div>

    <div class="col-md-2"></div>
  </div>
</div>

<br><br>
<div class="container">
  <div class="row">
    <%= @user.each do |user| %>
      <div class="col-md-4 mb-4">
        <div class="card" style="width: 18rem;">
          <%= image_tag "userimage" %>
          <div class="card-body">
            <h5 class="card-title"><%= user.first_name %></h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <%= link_to "view Profile", member_path(user), class: "btn btn-primary" %>

          </div>
      </div>
    </div>

    <%end%>

  </div>
  <br><br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Linkedln</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render '/shared/header' %>
    <%= yield %>
    <%= render '/shared/footer' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/members/show.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-4 mb-4">
        <div class="card" style="width: 18rem;">
          <%= image_tag "userimage" %>
          <div class="card-body">
            <h5 class="card-title"><%= @user.first_name %></h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <%= link_to "all User", root_path, class: "btn btn-primary" %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="py-5">
    <div class="row">
      <div class="col-2">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>

      <div class="col-2">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>

      <div class="col-2">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>

      <div class="col-4 offset-1">
        <form>
          <h5>Subscribe to our newsletter</h5>
          <p>Monthly digest of whats new and exciting from us.</p>
          <div class="d-flex w-100 gap-2">
            <label for="newsletter1" class="visually-hidden">Email address</label>
            <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
            <button class="btn btn-primary" type="button">Subscribe</button>
          </div>
        </form>
      </div>
    </div>

    <div class="d-flex justify-content-between py-4 my-4 border-top">
      <p>&copy; 2021 Company, Inc. All rights reserved.</p>
      <ul class="list-unstyled d-flex">
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
        <li class="ms-3"><a class="link-dark" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
      </ul>
    </div>
  </footer>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
     <li class="nav-item">
        <%= link_to 'All User Profile', root_path, class:'nav-link' %>
      </li>

      <% if user_signed_in?  %>
      <li class="nav-item">
        <%= link_to 'logout', destroy_user_session_path, class:'nav-link', data:{turbo_method: :delete} %>

      </li>
       <li class="nav-item">

        <%= link_to 'My profile', member_path(current_user), class:'nav-link' %>

      </li>


    <% else %>
      <li class="nav-item">
        <%= link_to 'Signin', new_user_session_path, class:'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Sign-Up', new_user_registration_path, class:'nav-link' %>
      </li>

    <% end  %>
    </ul>


  </div>
</nav>